NUM_CLASSES = 2
BATCH_SIZE = 1
NUM_EPOCHS = 100
DATASET_PATH = "./dataset/"
PLOT_PATH = "./plots/"
SEQUENCE_IDS_DICT_PATH = "./dataset/sequence_ids_dict.jsn"
ALL_SEQUENCES_PATH = "./dataset/all_sequences.csv"
FROZEN_REPRESENTATIONS_PATH = "./plm_representations/frozen_representations"
FINETUNED_REPRESENTATIONS_PATH = "./plm_representations/finetuned_representations"
FINETUNED_RESULTS_PATH = "./finetuned_results"
FINETUNED_MODELS_PATH = "./finetuned_models/"
FROZEN = "frozen"
FINETUNED = "finetuned"
MAX_LENGTH_FINETUNED = 1024
MAX_LENGTH_FROZEN = 4096
SEED = 42
TRAIN = "train"
VAL = "val"
TEST = "test"
IONCHANNELS = "ionchannels"
IONTRANSPORTERS = "iontransporters"
MEMBRANE_PROTEINS = "membrane_proteins"
IONCHANNELS_MEMBRANEPROTEINS = "ionchannels_membraneproteins"
IONCHANNELS_MEMBRANEPROTEINS_BALANCED = "ionchannels_membraneproteins_balanced"
IONCHANNELS_MEMBRANEPROTEINS_IMBALANCED = "ionchannels_membraneproteins_imbalanced"
IONCHANNELS_IONTRANSPORTERS = "ionchannels_iontransporters"
IONTRANSPORTERS_MEMBRANEPROTEINS = "iontransporters_membraneproteins"
IONTRANSPORTERS_MEMBRANEPROTEINS_BALANCED = "iontransporters_membraneproteins_balanced"
IONTRANSPORTERS_MEMBRANEPROTEINS_IMBALANCED = "iontransporters_membraneproteins_imbalanced"
TASK1 = {"name": "Task1", "description": "ionchannels vs. membrane proteins (imb) with frozen representations", "dataset": IONCHANNELS_MEMBRANEPROTEINS_IMBALANCED, "representation": FROZEN, "max_length": MAX_LENGTH_FROZEN}
TASK2 = {"name": "Task2", "description": "ionchannels vs. membrane proteins (imb) with finetuned representations", "dataset": IONCHANNELS_MEMBRANEPROTEINS_IMBALANCED, "representation": FINETUNED, "max_length": MAX_LENGTH_FINETUNED}
TASK3 = {"name": "Task3", "description": "ionchannels vs. membrane proteins (bal) with frozen representations", "dataset": IONCHANNELS_MEMBRANEPROTEINS_BALANCED, "representation": FROZEN, "max_length": MAX_LENGTH_FROZEN}
TASK4 = {"name": "Task4", "description": "ionchannels vs. membrane proteins (bal) with finetuned representations", "dataset": IONCHANNELS_MEMBRANEPROTEINS_BALANCED, "representation": FINETUNED, "max_length": MAX_LENGTH_FINETUNED}
TASK5 = {"name": "Task5", "description": "iontransporters vs. membrane proteins (imb) with frozen representations", "dataset": IONTRANSPORTERS_MEMBRANEPROTEINS_IMBALANCED, "representation": FROZEN, "max_length": MAX_LENGTH_FROZEN}
TASK6 = {"name": "Task6", "description": "iontransporters vs. membrane proteins (imb) with finetuned representations", "dataset": IONTRANSPORTERS_MEMBRANEPROTEINS_IMBALANCED, "representation": FINETUNED, "max_length": MAX_LENGTH_FINETUNED}
TASK7 = {"name": "Task7", "description": "iontransporters vs. membrane proteins (bal) with frozen representations", "dataset": IONTRANSPORTERS_MEMBRANEPROTEINS_BALANCED, "representation": FROZEN, "max_length": MAX_LENGTH_FROZEN}
TASK8 = {"name": "Task8", "description": "iontransporters vs. membrane proteins (bal) with finetuned representations", "dataset": IONTRANSPORTERS_MEMBRANEPROTEINS_BALANCED, "representation": FINETUNED, "max_length": MAX_LENGTH_FINETUNED}
TASK9 = {"name": "Task9", "description": "ionchannels vs. iontransporters with frozen representations", "dataset": IONCHANNELS_IONTRANSPORTERS, "representation": FROZEN, "max_length": MAX_LENGTH_FROZEN}
TASK10 = {"name": "Task10", "description": "ionchannels vs. iontransporters with finetuned representations", "dataset": IONCHANNELS_IONTRANSPORTERS, "representation": FINETUNED, "max_length": MAX_LENGTH_FINETUNED}
TASKS = [TASK1, TASK2, TASK3, TASK4, TASK5, TASK6, TASK7, TASK8, TASK9, TASK10]
PROTBERT = {"name": "ProtBERT", "model": "Rostlab/prot_bert"}
PROTBERTBFD = {"name": "ProtBERT-BFD", "model": "Rostlab/prot_bert_bfd"}
PROTT5 = {"name": "ProtT5", "model": "Rostlab/prot_t5_xl_half_uniref50-enc"}
ESM1B = {"name": "ESM-1b", "model": "facebook/esm1b_t33_650M_UR50S"}
ESM2 = {"name": "ESM-2", "model": "facebook/esm2_t33_650M_UR50D"}
ESM2_15B = {"name": "ESM-2_15B", "model": "facebook/esm2_t48_15B_UR50D"}
REPRESENTATIONS = [PROTBERT, PROTBERTBFD, PROTT5, ESM1B, ESM2, ESM2_15B]
